# Generated by Django 5.1.11 on 2025-08-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package')),
            ],
        ),
    ]
